version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hamadakafu/sample
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Setup CLOUD SDK 
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project spinnaker-kafu
            gcloud --quiet auth configure-docker
      - run: 
          name: Push docker image
          command: |
            docker build -t sample-spinnaker .
            TAG=gcr.io/spinnaker-kafu/sample-spinnaker:$CIRCLE_SHA1
            docker tag sample-spinnaker $TAG
            docker push $TAG
            LATEST_TAG=gcr.io/pospome-deployflow-project/go-web-server:latest
            docker tag sample-spinnaker $LATEST_TAG
            docker push $LATEST_TAG